# Copyright (c) 2015-2020 Clearmatics Technologies Ltd
#
# SPDX-License-Identifier: LGPL-3.0+

AGGREGATOR_SERVER_ENDPOINT_DEFAULT = "localhost:50052"

ZKSNARK_NAME_DEFAULT = "GROTH16"

BATCH_PROOF_FILENAME_DEFAULT = "batch.json"

AGGREGATOR_VERIFICATION_KEY_FILE_DEFAULT = "aggregator-vk.json"

INSTANCE_FILE_DEFAULT = "zecale-instance"

APPLICATION_INSTANCE_FILE_DEFAULT = "app-instance"
