# We use the same base image as zeth since we need
# the same dependencies
FROM clearmatics/zeth-base

# Copy the project in the docker container
COPY . /home/zecale

# Install the submodules
RUN cd /home/zecale && git submodule update --init --recursive

WORKDIR /home/zecale

CMD ["/bin/bash"]
