# We use the same base image as zeth since we need the same dependencies
FROM clearmatics/zeth-base

# Copy the project in the docker container
COPY . /home/zecale
WORKDIR /home/zecale

# Install the submodules
RUN git submodule update --init --recursive

CMD ["/bin/bash"]

