#!/usr/bin/env python3

# Copyright (c) 2015-2020 Clearmatics Technologies Ltd
#
# SPDX-License-Identifier: LGPL-3.0+

from zecale.commands.defaults import AGGREGATOR_SERVER_ENDPOINT_DEFAULT
from zecale.commands.command_context import CommandContext
from zecale.commands.zecale_register import register
from zecale.commands.zecale_submit import submit
from zecale.commands.zecale_get_batch import get_batch
from grpc import RpcError
from click import command, group, option, pass_context, Context, ClickException
from click_default_group import DefaultGroup
import sys


@command()
@pass_context
def help(ctx: Context) -> None:
    """
    Print help and exit
    """
    # Note, this command seems redundant but ensures that an error is raised if
    # no subcommand is specified.
    assert(ctx.parent)
    print(ctx.parent.get_help())
    raise ClickException("no command specified")


class HandleRpcExceptions(DefaultGroup):
    """
    A click group which handles uncaught RpcExceptions with a sensible message
    (similar to ClickException).
    """
    def __call__(self, *args, **kwargs):
        try:
            return DefaultGroup.__call__(self, *args, **kwargs)
        except RpcError as ex:
            print(f"error: {ex.details()}")
            sys.exit(1)


@group(cls=HandleRpcExceptions, default_if_no_args=True, default="help")
@option(
    "--aggregator-server", "-a",
    default=AGGREGATOR_SERVER_ENDPOINT_DEFAULT,
    help=f"Prover server endpoint (default={AGGREGATOR_SERVER_ENDPOINT_DEFAULT})")
@pass_context
def zecale(
        ctx: Context,
        aggregator_server: str) -> None:
    if ctx.invoked_subcommand == "help":
        ctx.invoke(help)
    ctx.obj = CommandContext(
        aggregator_server)


zecale.add_command(register)
zecale.add_command(submit)
zecale.add_command(get_batch)
zecale.add_command(help)


if __name__ == "__main__":
    zecale()  # pylint: disable=no-value-for-parameter
