#!/usr/bin/env bash

platform=`uname`
echo platform=${platform}
echo "running against commit: "`git log --oneline --no-decorate -n 1`

set -x
set -e

function check_format() {
    scripts/format
    git diff --no-ext-diff | head -n 20 > format_errors
    num_lines=`cat format_errors | wc -l`
    if [ "${num_lines}" != "0" ] ; then
        echo CODE FORMATTING ERRORS:
        cat format_errors
        exit 1
    fi

    # Perform the check for copyright notices here
    scripts/check_copyright
}

function check_cpp() {
    apk add cppcheck
    cppcheck --version

    # Configure and run cppcheck
    mkdir -p build
    pushd build
    cmake -DUSE_CPP_CHECK=ON ..
    make VERBOSE=1 cppcheck -j 5
    popd
}

function build() {
    # Enable warnings-as-errors
    # TODO: Uncomment, and support compilation with -Werror set
    #cxx_flags="-Werror"
    cxx_flags=""

    if [ "${platform}" == "Darwin" ] ; then
        openssl_path=$(brew --prefix openssl)
        export PATH="/usr/local/opt/llvm/bin:/usr/local/bin:${PATH}"
        export PKG_CONFIG_PATH="${openssl_path}/lib/pkgconfig"
        export LIBRARY_PATH="${openssl_path}/lib"
        export LDFLAGS="-L/usr/local/lib -L${openssl_path}/lib"
        export CPPFLAGS="-I/usr/local/include -I${openssl_path}/include"

        cxx_flags="${cxx_flags} -I${openssl_path}/include"
        cxx_flags="${cxx_flags} -Wno-deprecated-declarations"
    fi

    cmake_flags="-DCMAKE_BUILD_TYPE=${CI_CONFIG}"
    if ! [ "${full_build}" == "1" ] ; then
        cmake_flags="${cmake_flags} -DFAST_TESTS_ONLY=ON"
    fi

    # Build and run unit tests
    . setup_env.sh
    mkdir -p build
    cd build
    cmake                                    \
        ${cmake_flags}                       \
        -DCMAKE_CXX_FLAGS="${cxx_flags}"     \
        ..

    # TODO: Uncomment the line above when the build is repaired
    # for now let's just run the tests in the CI
    #make -j 2 VERBOSE=1 all build_tests

    # Compile the project first (this will generate all grpc/proto files)
    # in Zeth. These are also used in the tests
    make -j 2
    # Compile and run the tests
    make -j 2 check
    cd ..
}

function ci_setup() {

    if [ "${platform}" == "Darwin" ] ; then
        # Some of these commands can fail (if packages are already installed,
        # etc), hence the `|| echo`.
        brew unlink python@2
        brew update || echo
        brew install \
             gmp \
             grpc \
             protobuf \
             boost \
             openssl \
             cmake \
             libtool \
             autoconf \
             automake \
             python \
             || echo
    fi

    if [ "${platform}" == "Linux" ] ; then
        # `py3-virtualenv` depends on `python3`
        # which installs the latest version of python3
        # See: https://pkgs.alpinelinux.org/package/edge/main/x86/python3
        # https://build.alpinelinux.org/buildlogs/build-edge-x86/main/python3/python3-3.8.2-r6.log
        apk add \
            py3-virtualenv \
            libffi-dev \
            python3-dev
    fi
}


ci_task=$1
full_build=$2
if [ "${full_build}" == "" ] ; then
    if [ "${CI_EVENT_NAME}" == "pull_request" ] ; then
        full_build=1
    fi
fi

echo ci_task = ${ci_task}
echo full_build=${full_build}
echo CI_CONFIG=${CI_CONFIG}
echo CI_ZKSNARK=${CI_ZKSNARK}
echo CI_CHECK_FORMAT=${CI_CHECK_FORMAT}
echo CI_EVENT_NAME=${CI_EVENT_NAME}

if [ "${CI_CHECK_FORMAT}" == "1" ] ; then
    check_format
fi

# Fallback to PGHR13 until we fully support Groth16
if [ "${CI_ZKSNARK}" == "" ] ; then
    CI_ZKSNARK="PGHR13"
fi

# The CI_USE_DOCKER variable determines whether we should
# re-execute the script in the docker container with CI_USE_DOCKER=0
if [ "${CI_USE_DOCKER}" == "1" ] ; then
    docker pull clearmatics/zeth-base:latest
    docker build -f Dockerfile-zecale -t zecale-dev .
    docker run \
           -t \
           -p 50052:50052 \
           --name zecale \
           --env CI_CONFIG=${CI_CONFIG} \
           --env CI_ZKSNARK=${CI_ZKSNARK} \
           zecale-dev:latest $0 ${ci_task} ${full_build}
else
    ci_setup
    ${ci_task}
fi
