# Actions for pull requests only
name: zecale-ci-pull-request

on:
  pull_request:

jobs:

  onpr-build-grpc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/zeth/depends/grpc
    - name: Build grpc
      run: |
        pushd depends/zeth
        if ! [ -d depends/grpc ] ; then scripts/install-grpc /usr v1.31.x ; fi
        popd

  build-linux-full-tests:
    runs-on: ubuntu-20.04
    needs: [onpr-build-grpc]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/zeth/depends/grpc
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
        key: build-linux-full-tests-pip-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          depends/zeth/depends/ganache-cli/node_modules
        key: build-linux-full-tests-npm-${{ hashFiles('**/package-lock.json') }}-${{ runner.os }}
    - name: Install dependencies
      run: |
        pushd depends/zeth
        INSTALL_ONLY=1 scripts/install-grpc /usr v1.31.x
        popd
    - name: Execute
      run: CI_FULL_TESTS=1 CI_CONFIG=Release scripts/ci build

  build-linux-integration-tests:
    runs-on: ubuntu-20.04
    needs: [onpr-build-grpc]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/zeth/depends/grpc
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
        key: build-linux-integration-tests-pip-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          depends/zeth/depends/ganache-cli/node_modules
        key: build-linux-integration-tests-npm-${{ hashFiles('**/package-lock.json') }}-${{ runner.os }}
    - name: Install dependencies
      run: |
        pushd depends/zeth
        INSTALL_ONLY=1 scripts/install-grpc /usr v1.31.x
        popd
    - name: Execute
      run: CI_INTEGRATION_TESTS=1 CI_CONFIG=Release scripts/ci build
