# Actions for pull requests only
name: zecale-ci-pull-request

on:
  pull_request:

jobs:

  onpr-build-grpc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/grpc
    - name: Build grpc
      run: if ! [ -d depends/grpc ] ; then depends/zeth/scripts/install_grpc /usr v1.31.x depends/grpc ; fi

  build-linux-full:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/grpc
    - name: Install dependencies
      run: |
        depends/zeth/scripts/install_grpc /usr v1.31.x depends/grpc
    - name: Execute
      run: CI_EVENT_NAME=pull_request CI_CONFIG=Release scripts/ci build
